### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Encoder:

### ISSUE THREAD

**Issue by SunMingxuanSher** [THU-BPM/RAPL#1]
Hi Mr. Meng:

While I was running the model by using the comment provided by scripts/fredo_crossdomain_1doc.sh. 
I got the following errors:
![屏幕截图 2024-01-06 172542](https://github.com/THU-BPM/RAPL/assets/57325532/b0afc183-e74f-420a-a20d-5c6c3e3ead70)

I guess these is something needs to be modified in the models you shared in Qinghua cloud. And I am expecting for your updates. Thank you!

**Comment by msa30** [comment]
Hi, I speculate that this error may be related to the differences between various versions of transformers. You can try modifying the code at line 198 of main.py to "encoder.load_state_dict(torch.load(f"{args.load_checkpoint}"), strict=False)". If it doesn't work, you can try switching the transformers version to 3.4.0 to see if a similar error persists.
