### ISSUE TITLE
PytorchstreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by HiOTTO-Yuchen** [THU-BPM/RAPL#2]
Hi，   
   
When running the program, I noticed a discrepancy between the file size displayed on your Tsinghua cloud checkpoint and the actual size downloaded (the website displayed 885.6 MB but the actual download was 844.6 MB). Initially, I didn't pay much attention to it, but when I attempted to execute the program,  the error appears like the figure shows.

![RAPL运行失败](https://github.com/THU-BPM/RAPL/assets/160541267/77b0e915-2bee-406f-9e21-33a26a87a092)

After searching on the internet, I found that this error might be related to the incompleteness of the file being used. Therefore, I guese that the file on Tsinghua cloud might be incomplete or related to the browser I'm using. If possible, could you please share the download situation of yours and the browser you're using? Looking forward to your update.
    
Thank you.
    
Yu Chen

**Comment by msa30** [comment]
Hi, the size of the original checkpoint for refredo_indomain_3doc.pt should be 885596623 B (≈844.57 MB), so I think a size of 844.6 MB is expected. The size shown on the web page may be due to some specific handling of Tsinghua Cloud. You can try switching to another browser (Microsoft Edge works for me) and re-download the checkpoints. Additionally, you may also experiment with torch 1.9.0 version (if not) which works normally on my environment.

**Comment by HiOTTO-Yuchen** [comment]
Thank you, I will try it.

**Comment by HiOTTO-Yuchen** [comment]
Hi @locurryve, the solution of the environment works, but after that, it comes out a new issue. Like in this Figure
![RAPL新](https://github.com/THU-BPM/RAPL/assets/160541267/250c1cd2-ff54-4016-bf52-568f4fd66a0b)
In model.py file line 215, the size of tensor torch,cat([hs,rs],dim=1) doesn't match with the neural networks tensor head_extraction. In addition, while testing other .sh files in scripts directory, I found the size of tensor torch,cat([hs,rs],dim=1) are different, from [71, 1536] to [407,1536]. So I m wondering if there is anything I need to modified in the code. Thank you

**Comment by msa30** [comment]
According to the log, it seems that the size of tensor `torch.cat([hs, rs], dim=1)` matches well with the linear layer `head_extractor`: the former has a size of 1536 for dim 1, and the latter has a size of 1536 for in_features. The different sizes for dim 0 of `torch.cat([hs, rs], dim=1)` are caused by different numbers of NOTA instances. I wonder is there any error information is about memory usage or CUDA? This error is more likely caused by certain issues in the environment or library rather than code.

**Comment by HiOTTO-Yuchen** [comment]
> According to the log, it seems that the size of tensor `torch.cat([hs, rs], dim=1)` matches well with the linear layer `head_extractor`: the former has a size of 1536 for dim 1, and the latter has a size of 1536 for in_features. The different sizes for dim 0 of `torch.cat([hs, rs], dim=1)` are caused by different numbers of NOTA instances. I wonder is there any error information is about memory usage or CUDA? This error is more likely caused by certain issues in the environment or library rather than code.

Well, although I don't understand why different env can make such error. I did in my laptop, the dependency packages are the last version with torch 2.0.1, but just 6G GPU. I will try in some other envs. Thank you for your answer

**Comment by HiOTTO-Yuchen** [comment]
> According to the log, it seems that the size of tensor `torch.cat([hs, rs], dim=1)` matches well with the linear layer `head_extractor`: the former has a size of 1536 for dim 1, and the latter has a size of 1536 for in_features. The different sizes for dim 0 of `torch.cat([hs, rs], dim=1)` are caused by different numbers of NOTA instances. I wonder is there any error information is about memory usage or CUDA? This error is more likely caused by certain issues in the environment or library rather than code.

Hi, sorry for telling you, your advise doesn't work. I tried in the best server I can found(requirements.txt is attached). But still comes out the same error. So I think there is some other reasons caused this issue. 
[requirements.txt](https://github.com/THU-BPM/RAPL/files/14398105/requirements.txt)

**Comment by msa30** [comment]
The requirements seem all right. I've rerun the script and the current script parameters need about at least ~23GB GPU memory for running. Could you please provide the configuration of the server and the complete error information?

**Comment by HiOTTO-Yuchen** [comment]
Hi, @locurryve Here is the configuration of the server I use.

![屏幕截图 2024-02-28 202339](https://github.com/THU-BPM/RAPL/assets/160541267/ee9a480c-6927-42ae-9048-3f7c78934428)

And I run the comment(I m sure the pt is in the right dir): 

```
 sh scripts/refredo_crossdomain_3doc.sh
```

here is the complete error information like that:

```
found cached dataset. loading from dataset/cache/cached-test_scierc.json
Constructing episodes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 3000/3000 [00:03<00:00, 985.30it/s]loading model from checkpoints/refredo_crossdomain_3doc.pt
/root/miniconda3/envs/myconda/lib/python3.10/site-packages/transformers/optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/root/miniconda3/envs/myconda/lib/python3.10/site-packages/apex/__init__.py:68: DeprecatedFeatureWarning: apex.amp is deprecated and will be removed by the end of February 2023. Use [PyTorch AMP](https://pytorch.org/docs/stable/amp.html)
  warnings.warn(msg, DeprecatedFeatureWarning)
0it [00:00, ?it/s]
---- SCIERC TEST EVAL -----
  0%|                                                                                                                                              | 0/750 [00:00<?, ?it/s]cat size is torch.Size([147, 1536])

nn size is torch.Size([768, 1536])
  0%|                                                                                                                                              | 0/750 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/RAPL-main/src/main.py", line 460, in <module>
    output = encoder(exemplar_tokens.to('cuda'),
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/RAPL-main/src/model.py", line 216, in forward
    hs = torch.tanh(self.head_extractor(torch.cat([hs, rs], dim=1)))  # [pair_of_nota, hidden]
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range
```

An addition question, did you tried git clone this project in your env and run it?

**Comment by msa30** [comment]
Sorry for the late response. I also re-clone the project for validation and it works. In README, I've updated the versions of all packages in my experimental environment:

- apex 0.1
- numpy 1.19.4
- opt_einsum 3.3.0
- torch 1.9.0+cu111
- tqdm 4.64.0
- transformers 3.4.0
- wandb 0.12.21

Could you please try again using packages of above versions to see if it works properly? Hope this can provide some assistance.

**Comment by PEFT2026** [comment]
> Sorry for the late response. I also re-clone the project for validation and it works. In README, I've updated the versions of all packages in my experimental environment:
> 
> * apex 0.1
> * numpy 1.19.4
> * opt_einsum 3.3.0
> * torch 1.9.0+cu111
> * tqdm 4.64.0
> * transformers 3.4.0
> * wandb 0.12.21
> 
> Could you please try again using packages of above versions to see if it works properly? Hope this can provide some assistance.
I had the same problem,I want to ask you if you can run successfully under such a requirement without reporting errors

**Comment by PEFT2026** [comment]
这个应该是apex的bug，修改可以按照这个文章进行更改https://blog.csdn.net/starvapour/article/details/122275439

**Comment by HiOTTO-Yuchen** [comment]
> Sorry for the late response. I also re-clone the project for validation and it works. In README, I've updated the versions of all packages in my experimental environment:
> 
> * apex 0.1
> * numpy 1.19.4
> * opt_einsum 3.3.0
> * torch 1.9.0+cu111
> * tqdm 4.64.0
> * transformers 3.4.0
> * wandb 0.12.21
> 
> Could you please try again using packages of above versions to see if it works properly? Hope this can provide some assistance.

OK, I will have a try.

**Comment by HiOTTO-Yuchen** [comment]
> 这个应该是apex的bug，修改可以按照这个文章进行更改https://blog.csdn.net/starvapour/article/details/122275439

行，我试试

**Comment by HiOTTO-Yuchen** [comment]
> 这个应该是apex的bug，修改可以按照这个文章进行更改https://blog.csdn.net/starvapour/article/details/122275439

好使，谢谢哥们

**Comment by HiOTTO-Yuchen** [comment]
> Sorry for the late response. I also re-clone the project for validation and it works. In README, I've updated the versions of all packages in my experimental environment:
> 
> * apex 0.1
> * numpy 1.19.4
> * opt_einsum 3.3.0
> * torch 1.9.0+cu111
> * tqdm 4.64.0
> * transformers 3.4.0
> * wandb 0.12.21
> 
> Could you please try again using packages of above versions to see if it works properly? Hope this can provide some assistance.

Hi, I tried the advice by @dengxingzhi with my own envs, it works. I guess is the bug of apex in github instead of the issue in envs. And thank you for tracking my issue for such long time!

**Comment by msa30** [comment]
I see, so that's how matters stand. Thanks for @dengxingzhi 's solution~
