### ISSUE TITLE
关于数据集中训练，评估，测试的关系类型分布问题

### ISSUE THREAD

**Issue by passengeryjy** [THU-BPM/RAPL#3]
作者您好。请问一下，在您提供的训练、评估，测试集中，是如何保证关系类型总数分别为62、16，18的呢？想问下有处理代码吗

**Comment by msa30** [comment]
您好，以训练集为例，只需要保留每篇文章“labels”字段中关系类型在训练集关系类型集合的那些关系三元组，其他字段保持不变即可。
